# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        anaxago_provider:
            entity:
                class: App\Entity\User
                property: apiKey

    firewalls:
        api:
            anonymous: true
            pattern: ^/api/anonymous
            stateless: true

        api-user:
            anonymous: false
            pattern: ^/api
            stateless: true
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator

        main:
            provider: anaxago_provider
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - App\Security\AppAnaxagoAuthenticator
                entry_point: App\Security\AppAnaxagoAuthenticator
            logout:
                path: app_logout
                target: /