anaxago_starter:
    resource: "routes/default/routing.yml"
    prefix:   /

anaxago_security:
    resource: "routes/security/routing.yml"
    prefix:   /

project:
    type: annotation
    resource: App\Controller\ProjectController
