anaxago_starter:
    resource: "routes/default/routing.yml"
    prefix:   /

anaxago_security:
    resource: "routes/security/routing.yml"
    prefix:   /

projects:
    type: rest
    resource: App\Controller\ProjectController
    prefix: /api
